# Generated by Django 5.1.2 on 2025-03-16 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_profileinformation_source'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='source',
        ),
        migrations.AddField(
            model_name='source',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source', to='home.profileinformation'),
        ),
        migrations.AddField(
            model_name='source',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source', to='posts.tag'),
        ),
    ]
