# Generated by Django 5.1.2 on 2025-03-16 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_profileinformation_source'),
        ('posts', '0002_remove_tag_source_source_profile_source_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_source', to='home.profileinformation'),
        ),
        migrations.AlterField(
            model_name='source',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag_source', to='posts.tag'),
        ),
    ]
