# Generated by Django 5.1.2 on 2024-11-26 19:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=255)),
                ('app_real_name', models.CharField(max_length=255)),
                ('descriptions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, size=None)),
                ('url', models.URLField(blank=True, null=True)),
                ('image_url', models.URLField()),
            ],
        ),
    ]
