# Generated by Django 5.1.2 on 2025-03-20 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('secondary_name', models.CharField(blank=True, max_length=255)),
                ('descriptions', models.JSONField()),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
