# Generated by Django 5.1.2 on 2025-03-16 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('secondary_name', models.CharField(blank=True, max_length=255)),
                ('descriptions', models.JSONField()),
                ('url', models.URLField(blank=True, null=True)),
                ('source', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_information', to='posts.source')),
            ],
        ),
    ]
